//! Live, template-aware OpenAPI document (specs/003-open-source-project, R2).
//!
//! The static document (generic routes, generated by `utoipa`) is extended at request time with
//! one typed render operation per valid template, whose request body is the template's own
//! schema. The result is cached until the registry snapshot changes (hot reload replaces the
//! whole map, so its identity is enough). Contract:
//! specs/003-open-source-project/contracts/live-openapi.md.

use std::collections::BTreeSet;
use std::sync::{Arc, Mutex, Weak};

use axum::body::Bytes;
use serde_json::{Map, Value, json};

use crate::registry::{Registry, TemplateEntry, TemplateMap};

/// Path of the generic render operation, whose parameters and responses are reused.
const GENERIC_RENDER: &str = "/templates/{templateId}/render";
/// Tag grouping the per-template operations.
const LIVE_TAG: &str = "templates (live)";

/// Cache of the serialized live document.
#[derive(Default)]
pub struct LiveDoc {
    cache: Mutex<Option<(Weak<TemplateMap>, Bytes)>>,
}

impl LiveDoc {
    /// JSON bytes of the document for the current registry snapshot.
    pub fn get(&self, registry: &Registry) -> Bytes {
        let snapshot = registry.snapshot();
        let mut cache = self.cache.lock().expect("live OpenAPI cache poisoned");
        if let Some((weak, bytes)) = cache.as_ref()
            && weak
                .upgrade()
                .is_some_and(|current| Arc::ptr_eq(&current, &snapshot))
        {
            return bytes.clone();
        }
        let base = serde_json::to_value(super::openapi()).expect("serializable OpenAPI document");
        let document = build(&base, snapshot.values().map(Arc::as_ref));
        let bytes = Bytes::from(serde_json::to_vec(&document).expect("serializable document"));
        *cache = Some((Arc::downgrade(&snapshot), bytes.clone()));
        bytes
    }
}

/// Adds one typed operation per valid template to `base`.
pub fn build<'a>(base: &Value, templates: impl IntoIterator<Item = &'a TemplateEntry>) -> Value {
    let mut document = base.clone();
    let Some(generic) = base["paths"][GENERIC_RENDER]["post"].as_object().cloned() else {
        return document;
    };
    let mut taken: BTreeSet<String> = document["components"]["schemas"]
        .as_object()
        .map(|schemas| schemas.keys().cloned().collect())
        .unwrap_or_default();

    let mut added = false;
    for entry in templates {
        let Some(schema) = entry.schema.as_ref().filter(|_| entry.is_valid()) else {
            continue;
        };
        let id = entry.id.as_str();
        let prefix = unique_prefix(id, &mut taken);
        let root = schema.value();

        let mut components = Map::new();
        if let Some(defs) = root.get("$defs").and_then(Value::as_object) {
            for (name, def) in defs {
                components.insert(format!("{prefix}_{name}"), clean(def, &prefix));
            }
        }
        let mut properties = Map::new();
        for (key, suffix) in [("data", "Data"), ("layout", "Layout")] {
            if let Some(sub) = root.pointer(&format!("/properties/{key}")) {
                let name = format!("{prefix}{suffix}");
                components.insert(name.clone(), clean(sub, &prefix));
                properties.insert(key.to_owned(), json!({ "$ref": schema_ref(&name) }));
            }
        }
        properties.insert(
            "metadata".into(),
            json!({ "$ref": schema_ref("DocumentMetadata") }),
        );
        let request = format!("{prefix}RenderRequest");
        components.insert(
            request.clone(),
            json!({
                "type": "object",
                "additionalProperties": false,
                "required": root.get("required").cloned().unwrap_or_else(|| json!(["data"])),
                "properties": properties,
            }),
        );
        for name in components.keys() {
            taken.insert(name.clone());
        }

        let mut operation = generic.clone();
        operation.insert(
            "operationId".into(),
            json!(format!("render_{}", id.replace('-', "_"))),
        );
        operation.insert("tags".into(), json!([LIVE_TAG]));
        operation.insert("summary".into(), json!(entry.name));
        let mut description = entry.description.clone().unwrap_or_default();
        if let Some(version) = &entry.version {
            description = format!("{description} (version {version})")
                .trim()
                .to_owned();
        }
        operation.insert("description".into(), json!(description));
        if let Some(Value::Array(parameters)) = operation.get_mut("parameters") {
            parameters.retain(|p| p["in"] != "path");
        }
        operation.insert(
            "requestBody".into(),
            json!({
                "required": true,
                "content": { "application/json": { "schema": { "$ref": schema_ref(&request) } } },
            }),
        );

        document["paths"][format!("/templates/{id}/render")] = json!({ "post": operation });
        if let Some(schemas) = document["components"]["schemas"].as_object_mut() {
            schemas.extend(components);
        }
        added = true;
    }

    if added && let Some(tags) = document["tags"].as_array_mut() {
        tags.push(json!({
            "name": LIVE_TAG,
            "description": "One typed render operation per valid template currently loaded.",
        }));
    }
    document
}

fn schema_ref(name: &str) -> String {
    format!("#/components/schemas/{name}")
}

/// `progress-invoice` → `ProgressInvoice`, made unique among `taken`.
fn unique_prefix(id: &str, taken: &mut BTreeSet<String>) -> String {
    let base: String = id
        .split(['-', '_'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            chars
                .next()
                .map(|first| first.to_uppercase().chain(chars).collect::<String>())
                .unwrap_or_default()
        })
        .collect();
    let clashes = |candidate: &str, taken: &BTreeSet<String>| {
        taken
            .iter()
            .any(|name| name == candidate || name.starts_with(&format!("{candidate}_")))
            || taken.contains(&format!("{candidate}RenderRequest"))
    };
    let mut candidate = base.clone();
    let mut n = 2;
    while clashes(&candidate, taken) {
        candidate = format!("{base}{n}");
        n += 1;
    }
    taken.insert(format!("{candidate}RenderRequest"));
    candidate
}

/// Copy of a sub-schema: `$schema`, `$id` and `$defs` removed, internal references rewritten
/// into component references.
fn clean(schema: &Value, prefix: &str) -> Value {
    let mut copy = schema.clone();
    if let Some(object) = copy.as_object_mut() {
        object.remove("$schema");
        object.remove("$id");
        object.remove("$defs");
    }
    rewrite_refs(&mut copy, prefix);
    copy
}

/// Rewrites `#/$defs/x…`, `#/properties/data…` and `#/properties/layout…` pointers.
fn rewrite_refs(value: &mut Value, prefix: &str) {
    match value {
        Value::Object(object) => {
            for (key, child) in object.iter_mut() {
                if key == "$ref" {
                    if let Some(reference) = child.as_str() {
                        *child = json!(rewrite_ref(reference, prefix));
                    }
                } else {
                    rewrite_refs(child, prefix);
                }
            }
        }
        Value::Array(items) => items.iter_mut().for_each(|item| rewrite_refs(item, prefix)),
        _ => {}
    }
}

fn rewrite_ref(reference: &str, prefix: &str) -> String {
    if let Some(rest) = reference.strip_prefix("#/$defs/") {
        let (name, tail) = rest.split_once('/').map_or((rest, ""), |(n, t)| (n, t));
        let tail = if tail.is_empty() {
            String::new()
        } else {
            format!("/{tail}")
        };
        return format!("{}{tail}", schema_ref(&format!("{prefix}_{name}")));
    }
    for (key, suffix) in [("data", "Data"), ("layout", "Layout")] {
        if let Some(tail) = reference.strip_prefix(&format!("#/properties/{key}")) {
            return format!("{}{tail}", schema_ref(&format!("{prefix}{suffix}")));
        }
    }
    reference.to_owned()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn prefixes_are_pascal_case_and_unique() {
        let mut taken = BTreeSet::new();
        assert_eq!(
            unique_prefix("progress-invoice", &mut taken),
            "ProgressInvoice"
        );
        assert_eq!(unique_prefix("a-b", &mut taken), "AB");
        assert_eq!(unique_prefix("a_b", &mut taken), "AB2");
        assert_eq!(unique_prefix("sample", &mut taken), "Sample");
    }

    #[test]
    fn internal_references_are_rewritten() {
        assert_eq!(
            rewrite_ref("#/$defs/amount", "P"),
            "#/components/schemas/P_amount"
        );
        assert_eq!(
            rewrite_ref("#/$defs/line/properties/code", "P"),
            "#/components/schemas/P_line/properties/code"
        );
        assert_eq!(
            rewrite_ref("#/properties/data/properties/x", "P"),
            "#/components/schemas/PData/properties/x"
        );
        assert_eq!(
            rewrite_ref("#/components/schemas/X", "P"),
            "#/components/schemas/X"
        );
    }

    #[test]
    fn cleaned_copies_drop_schema_keywords() {
        let schema = json!({
            "$schema": "x", "$id": "y", "$defs": {},
            "properties": { "a": { "$ref": "#/$defs/a" } }
        });
        assert_eq!(
            clean(&schema, "P"),
            json!({ "properties": { "a": { "$ref": "#/components/schemas/P_a" } } })
        );
    }
}
