//! Generated reference pages of the documentation site (`docs/src/reference/`).
//!
//! - `api.md` from `openapi/openapi.json` (the locked, template-free document);
//! - `errors.md` from `crates/inkpdf/src/error.rs` (codes, HTTP statuses, titles);
//! - `packages.md` from `packages/lock.toml` and the vendored archives.
//!
//! `check` also verifies that every `INKPDF_*` variable read by the service is documented in the
//! hand-written `configuration.md`.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow, bail};
use serde_json::Value;

use crate::lock::{self, Lock, Role};

/// First line of every generated page.
pub const GENERATED: &str = "<!-- generated by `cargo xtask docs generate`; do not edit -->";

struct Page {
    path: PathBuf,
    content: String,
}

fn pages(root: &Path) -> Result<Vec<Page>> {
    let reference = root.join("docs/src/reference");
    let openapi: Value = serde_json::from_slice(
        &fs::read(root.join("openapi/openapi.json")).context("reading openapi/openapi.json")?,
    )?;
    let errors = fs::read_to_string(root.join("crates/inkpdf/src/error.rs"))?;
    Ok(vec![
        Page {
            path: reference.join("api.md"),
            content: api_md(&openapi),
        },
        Page {
            path: reference.join("errors.md"),
            content: errors_md(&errors)?,
        },
        Page {
            path: reference.join("packages.md"),
            content: packages_md(root)?,
        },
    ])
}

pub fn generate(root: &Path) -> Result<()> {
    for page in pages(root)? {
        fs::create_dir_all(page.path.parent().unwrap())?;
        fs::write(&page.path, &page.content)?;
        println!(
            "wrote {}",
            page.path.strip_prefix(root).unwrap_or(&page.path).display()
        );
    }
    Ok(())
}

pub fn check(root: &Path) -> Result<()> {
    let mut stale = Vec::new();
    for page in pages(root)? {
        if fs::read_to_string(&page.path).ok().as_deref() != Some(page.content.as_str()) {
            stale.push(
                page.path
                    .strip_prefix(root)
                    .unwrap_or(&page.path)
                    .display()
                    .to_string(),
            );
        }
    }
    let config = fs::read_to_string(root.join("crates/inkpdf/src/config.rs"))?;
    let documented =
        fs::read_to_string(root.join("docs/src/reference/configuration.md")).unwrap_or_default();
    let missing: Vec<String> = config_variables(&config)
        .into_iter()
        .filter(|var| !documented.contains(var.as_str()))
        .collect();

    if !stale.is_empty() {
        eprintln!(
            "out of date (run `cargo xtask docs generate`): {}",
            stale.join(", ")
        );
    }
    if !missing.is_empty() {
        eprintln!(
            "not documented in docs/src/reference/configuration.md: {}",
            missing.join(", ")
        );
    }
    if stale.is_empty() && missing.is_empty() {
        println!("generated documentation is up to date");
        Ok(())
    } else {
        bail!("documentation check failed")
    }
}

/// `INKPDF_*` variables read in `config.rs`.
fn config_variables(source: &str) -> BTreeSet<String> {
    source
        .split('"')
        .filter(|chunk| {
            chunk.starts_with("INKPDF_")
                && chunk.chars().all(|c| c.is_ascii_uppercase() || c == '_')
        })
        .map(str::to_owned)
        .collect()
}

fn cell(text: &str) -> String {
    text.replace('|', "\\|").replace('\n', " ")
}

/// Reference of the generic HTTP API.
fn api_md(openapi: &Value) -> String {
    let mut out = format!(
        "{GENERATED}\n\n# HTTP API\n\n\
This page lists the **generic** routes of inkpdf, generated from the locked OpenAPI document\n\
(`openapi/openapi.json`).\n\n\
A running instance publishes a richer document: `GET /openapi.json` adds one typed render\n\
operation per template currently loaded (`POST /templates/<id>/render`, whose request body is\n\
that template's own schema), and `GET /docs` renders it interactively. Point an OpenAPI\n\
generator at a running instance to get a client typed per template.\n\n\
Errors use RFC 9457 `application/problem+json` bodies; see [Error codes](errors.md).\n"
    );
    let Some(paths) = openapi["paths"].as_object() else {
        return out;
    };
    for (path, item) in paths {
        let Some(methods) = item.as_object() else {
            continue;
        };
        for (method, op) in methods {
            out.push_str(&format!("\n## `{} {path}`\n\n", method.to_uppercase()));
            if let Some(summary) = op["summary"].as_str() {
                out.push_str(&format!("**{}**\n\n", summary.trim()));
            }
            if let Some(description) = op["description"].as_str() {
                out.push_str(&format!("{}\n\n", description.trim()));
            }
            if let Some(params) = op["parameters"].as_array().filter(|p| !p.is_empty()) {
                out.push_str("| Parameter | In | Required | Description |\n|---|---|---|---|\n");
                for p in params {
                    out.push_str(&format!(
                        "| `{}` | {} | {} | {} |\n",
                        p["name"].as_str().unwrap_or(""),
                        p["in"].as_str().unwrap_or(""),
                        if p["required"].as_bool().unwrap_or(false) {
                            "yes"
                        } else {
                            "no"
                        },
                        cell(p["description"].as_str().unwrap_or("")),
                    ));
                }
                out.push('\n');
            }
            if let Some(content) = op["requestBody"]["content"].as_object() {
                for (media, body) in content {
                    let schema = body["schema"]["$ref"]
                        .as_str()
                        .and_then(|r| r.rsplit('/').next())
                        .map(|name| format!("`{name}`"))
                        .unwrap_or_else(|| "see the OpenAPI document".into());
                    out.push_str(&format!("Request body: `{media}`, schema {schema}.\n\n"));
                }
            }
            if let Some(responses) = op["responses"].as_object() {
                out.push_str("| Status | Description |\n|---|---|\n");
                for (status, response) in responses {
                    let description = response["description"]
                        .as_str()
                        .map(str::to_owned)
                        .or_else(|| {
                            response["$ref"].as_str().map(|r| {
                                format!("Problem ({})", r.rsplit('/').next().unwrap_or(""))
                            })
                        })
                        .unwrap_or_default();
                    out.push_str(&format!("| {status} | {} |\n", cell(&description)));
                }
            }
        }
    }
    out
}

/// Parses the `Self::Variant => value` arms of the `fn <name>` match in `error.rs`.
fn match_arms(source: &str, function: &str) -> Result<Vec<(Vec<String>, String)>> {
    let start = source
        .find(&format!("fn {function}("))
        .ok_or_else(|| anyhow!("fn {function} not found in error.rs"))?;
    let body = &source[start..];
    let end = body.find("\n    }\n").unwrap_or(body.len());
    let mut arms = Vec::new();
    for line in body[..end].lines() {
        let Some((left, right)) = line.trim().split_once("=>") else {
            continue;
        };
        let variants: Vec<String> = left
            .split('|')
            .filter_map(|v| {
                v.trim()
                    .strip_prefix("Self::")
                    .map(|v| v.split(['{', ' ']).next().unwrap().to_owned())
            })
            .collect();
        if !variants.is_empty() {
            arms.push((variants, right.trim().trim_end_matches(',').to_owned()));
        }
    }
    Ok(arms)
}

fn http_status(name: &str) -> Option<u16> {
    Some(match name.strip_prefix("StatusCode::")? {
        "BAD_REQUEST" => 400,
        "NOT_FOUND" => 404,
        "CONFLICT" => 409,
        "PAYLOAD_TOO_LARGE" => 413,
        "UNSUPPORTED_MEDIA_TYPE" => 415,
        "UNPROCESSABLE_ENTITY" => 422,
        "INTERNAL_SERVER_ERROR" => 500,
        "SERVICE_UNAVAILABLE" => 503,
        "GATEWAY_TIMEOUT" => 504,
        _ => return None,
    })
}

/// Reference of the error codes.
fn errors_md(error_rs: &str) -> Result<String> {
    let lookup = |function: &str| -> Result<BTreeMap<String, String>> {
        Ok(match_arms(error_rs, function)?
            .into_iter()
            .flat_map(|(variants, value)| variants.into_iter().map(move |v| (v, value.clone())))
            .collect())
    };
    let codes = lookup("as_str")?;
    let statuses = lookup("status")?;
    let titles = lookup("title")?;

    let mut rows: Vec<(u16, String, String)> = Vec::new();
    for (variant, code) in &codes {
        let status = statuses
            .get(variant)
            .and_then(|s| http_status(s))
            .ok_or_else(|| anyhow!("no known HTTP status for {variant}"))?;
        let title = titles.get(variant).cloned().unwrap_or_default();
        rows.push((
            status,
            code.trim_matches('"').to_owned(),
            title.trim_matches('"').to_owned(),
        ));
    }
    rows.sort();
    let mut out = format!(
        "{GENERATED}\n\n# Error codes\n\n\
Every error response is an RFC 9457 `application/problem+json` body with a machine-readable\n\
`code`. Validation errors add `violations[]` (JSON Pointers into the request body and the\n\
schema); rendering errors add `diagnostics[]` (message, file, line, column, hints). Files\n\
inside a bundled package are shown as `@preview/<name>:<version>/<path>`.\n\n\
| HTTP status | `code` | Title |\n|---|---|---|\n"
    );
    for (status, code, title) in rows {
        out.push_str(&format!("| {status} | `{code}` | {title} |\n"));
    }
    Ok(out)
}

/// Reference of the bundled Typst packages.
fn packages_md(root: &Path) -> Result<String> {
    let lock = Lock::read(root)?;
    let mut entries = lock.package.clone();
    entries.sort_by_key(|e| e.key());

    let mut info = BTreeMap::new();
    for entry in &entries {
        let archive = fs::read(Lock::vendor(root).join(entry.archive_name()))
            .with_context(|| format!("archive of {} {}", entry.name, entry.version))?;
        let files = lock::archive_files(&archive)?;
        let manifest = lock::manifest(&files)?;
        let description = manifest
            .get("description")
            .and_then(|d| d.as_str())
            .unwrap_or("")
            .trim()
            .to_owned();
        let wasm = files.keys().any(|path| path.ends_with(".wasm"));
        info.insert(
            (entry.name.clone(), entry.version.clone()),
            (description, wasm),
        );
    }

    let mut out = format!(
        "{GENERATED}\n\n# Bundled packages\n\n\
These [Typst Universe](https://typst.app/universe) packages are embedded in the inkpdf binary;\n\
nothing is ever downloaded. Import them **by name only** — the service uses the installed\n\
version (see [Bundled packages](../concepts/packages.md)). A running instance lists them at\n\
`GET /packages`.\n\n\
## Available packages\n\n\
| Import | Description | Version | License | WASM |\n|---|---|---|---|---|\n"
    );
    for entry in entries.iter().filter(|e| e.role == Role::Selected) {
        let (description, wasm) = &info[&(entry.name.clone(), entry.version.clone())];
        out.push_str(&format!(
            "| `@preview/{}` | {} | {} | {} | {} |\n",
            entry.name,
            cell(description),
            entry.version,
            entry.license,
            if *wasm { "yes" } else { "" },
        ));
    }
    out.push_str(
        "\n**WASM**: the package contains a compiled plugin. It runs inside the engine without\n\
network or file access, but a very long plugin call cannot be interrupted before it ends;\n\
see [Limits and performance](../operations/limits.md).\n\n\
## Licenses\n\n\
Every bundled package, including internal dependencies that templates cannot import. Each\n\
package ships with its license text inside the binary.\n\n\
| Package | Version | Role | License |\n|---|---|---|---|\n",
    );
    for entry in &entries {
        out.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            entry.name,
            entry.version,
            match entry.role {
                Role::Selected => "available to templates",
                Role::Dependency => "dependency",
            },
            entry.license,
        ));
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn api_page_lists_every_operation() {
        let openapi = json!({
            "paths": {
                "/a": { "get": { "summary": "A", "responses": { "200": { "description": "ok" } } } },
                "/b/{id}": { "post": {
                    "parameters": [{ "name": "id", "in": "path", "required": true, "description": "Id" }],
                    "requestBody": { "content": { "application/json": { "schema": { "$ref": "#/components/schemas/Body" } } } },
                    "responses": { "404": { "$ref": "#/components/responses/Problem" } }
                } }
            }
        });
        let page = api_md(&openapi);
        assert!(page.starts_with(GENERATED));
        assert!(page.contains("## `GET /a`"));
        assert!(page.contains("## `POST /b/{id}`"));
        assert!(page.contains("| `id` | path | yes | Id |"));
        assert!(page.contains("schema `Body`"));
        assert!(page.contains("| 404 | Problem (Problem) |"));
    }

    #[test]
    fn error_page_matches_the_service_source() {
        let source =
            fs::read_to_string(crate::repo_root().join("crates/inkpdf/src/error.rs")).unwrap();
        let page = errors_md(&source).unwrap();
        for (status, code) in [
            (404, "template-not-found"),
            (400, "invalid-parameter"),
            (422, "validation-failed"),
            (504, "render-timeout"),
        ] {
            assert!(
                page.contains(&format!("| {status} | `{code}` |")),
                "{code}\n{page}"
            );
        }
    }

    #[test]
    fn packages_page_lists_selected_imports_and_all_licenses() {
        let page = packages_md(&crate::repo_root()).unwrap();
        let lock = Lock::read(&crate::repo_root()).unwrap();
        for entry in &lock.package {
            if entry.role == Role::Selected {
                assert!(
                    page.contains(&format!("`@preview/{}`", entry.name)),
                    "{}",
                    entry.name
                );
            }
            assert!(
                page.contains(&format!("| {} | {} |", entry.name, entry.version)),
                "{}",
                entry.name
            );
        }
    }

    #[test]
    fn configuration_variables_are_extracted() {
        let vars =
            config_variables(r#"var("INKPDF_LISTEN") … var("INKPDF_DEFAULT_AUTHOR") "not_me""#);
        assert_eq!(
            vars.into_iter().collect::<Vec<_>>(),
            ["INKPDF_DEFAULT_AUTHOR", "INKPDF_LISTEN"]
        );
    }
}
