//! Typst packages bundled into the binary (specs/002-typst-packages).
//!
//! The list comes from `packages/lock.toml`; `build.rs` verifies the archives and generates a
//! static table. A `selected` package is offered to templates (one version per name); the
//! others only serve the packages' internal imports.

use std::collections::HashMap;
use std::sync::LazyLock;

use typst::foundations::Bytes;
use typst::syntax::package::PackageSpec;

/// Namespace of the bundled packages (Typst Universe).
pub const NAMESPACE: &str = "preview";

/// Entry generated by `build.rs`.
pub(crate) struct BundledPackageDef {
    name: &'static str,
    version: &'static str,
    description: &'static str,
    license: &'static str,
    selected: bool,
    entrypoint: &'static str,
    files: &'static [(&'static str, &'static [u8])],
}

include!(concat!(env!("OUT_DIR"), "/bundled_packages.rs"));

/// Bundled package, ready to be served to the engine.
pub struct BundledPackage {
    def: &'static BundledPackageDef,
    spec: PackageSpec,
    /// Relative path (`/`-separated) → content, without copying the static data.
    files: HashMap<&'static str, Bytes>,
}

impl BundledPackage {
    pub fn name(&self) -> &'static str {
        self.def.name
    }

    pub fn version(&self) -> &'static str {
        self.def.version
    }

    pub fn description(&self) -> &'static str {
        self.def.description
    }

    pub fn license(&self) -> &'static str {
        self.def.license
    }

    /// True if this version is the one offered to templates.
    pub fn is_selected(&self) -> bool {
        self.def.selected
    }

    pub fn entrypoint(&self) -> &'static str {
        self.def.entrypoint
    }

    /// `@preview/<name>:<version>`.
    pub fn spec(&self) -> &PackageSpec {
        &self.spec
    }

    /// Package file by relative path (without a leading `/`).
    pub fn file(&self, path: &str) -> Option<&Bytes> {
        self.files.get(path)
    }

    /// Paths of the package's files.
    pub fn paths(&self) -> impl Iterator<Item = &'static str> + '_ {
        self.def.files.iter().map(|(path, _)| *path)
    }
}

static PACKAGES: LazyLock<Vec<BundledPackage>> = LazyLock::new(|| {
    BUNDLED
        .iter()
        .map(|def| BundledPackage {
            def,
            spec: format!("@{NAMESPACE}/{}:{}", def.name, def.version)
                .parse()
                .expect("build.rs validates names and versions"),
            files: def
                .files
                .iter()
                .map(|(path, data)| (*path, Bytes::new(*data)))
                .collect(),
        })
        .collect()
});

/// All bundled packages, sorted by name then version.
pub fn all() -> &'static [BundledPackage] {
    &PACKAGES
}

/// Package that exactly matches `spec` (namespace, name, version).
pub fn get(spec: &PackageSpec) -> Option<&'static BundledPackage> {
    if spec.namespace != NAMESPACE {
        return None;
    }
    all().iter().find(|p| p.spec == *spec)
}

/// Version offered to templates for `name`.
pub fn selected(name: &str) -> Option<&'static BundledPackage> {
    all().iter().find(|p| p.is_selected() && p.name() == name)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn spec(s: &str) -> PackageSpec {
        s.parse().unwrap()
    }

    #[test]
    fn validated_list_is_bundled() {
        assert_eq!(all().len(), 28);
        assert_eq!(all().iter().filter(|p| p.is_selected()).count(), 20);
    }

    #[test]
    fn selected_version_is_the_one_offered_to_templates() {
        assert_eq!(selected("zero").unwrap().version(), "0.7.1");
        assert!(selected("komet").is_none(), "dependency only");
        assert!(selected("does-not-exist").is_none());
    }

    #[test]
    fn get_matches_exactly() {
        assert!(get(&spec("@preview/zero:0.6.1")).is_some());
        assert!(get(&spec("@preview/zero:0.5.0")).is_none());
        assert!(get(&spec("@local/zero:0.7.1")).is_none());
    }

    #[test]
    fn entrypoint_and_manifest_are_served() {
        for package in all() {
            assert!(
                package.file(package.entrypoint()).is_some(),
                "{}",
                package.name()
            );
            assert!(package.file("typst.toml").is_some(), "{}", package.name());
        }
    }
}
